name: Generate Snake Animation

on:
  # Trigger the workflow on a schedule
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight (UTC)
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Generate the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: remigere
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Upload the snake.svg
      - uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg
