name: Generate Snake Animation

on:
  # Run automatically every day
  schedule:
    - cron: "0 0 * * *"
  
  # Allow manual run
  workflow_dispatch:
  
  # Run on push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write  # Give the workflow permission to write to the repository
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake SVG
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Update the README.md with the new SVG paths
      - name: Update README.md
        run: |
          sed -i '/^### GitHub Contribution Snake/c\### GitHub Contribution Snake\n![GitHub Snake](./dist/github-contribution-grid-snake.svg)\n![GitHub Snake Dark](./dist/github-contribution-grid-snake-dark.svg)' README.md

      # Commit the changes to the README.md and SVGs to the main branch
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg
          git commit -m "Updated GitHub Contribution Snake in README"
          git push

